name: Feature request
description: Suggest an idea for DuckLoader or DuckAPI
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Is your request related to a problem or limitation you're running into?
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you've considered
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
    validations:
      required: false
